const mongoose = require('mongoose');

const incidentSchema = new mongoose.Schema({
    // _id: {type:mongoose.Schema.Types.ObjectId},
    _id: String,
    member: String,
    brands: String,
    incidentParentId: String,
    type: String,
    incidentClass: String,
    incidentSubject: String,
    preAuthorised: Boolean,
    authorizationEvidence: String,
    severity: String,
    status: String,
    snapshot: String,
    creationDate: Date,
    lastUpdateDate: Date,
    fraudCasting: Boolean,
    baiting: Boolean,
    suggestedCOA: String,
    actualCOA: String,
    feedbackProvidedByMember: String,
    memberRequestedCourseOfAction: String,
    // feedbackProvidedByMember: Boolean,
    // memberRequestedCourseOfAction: Boolean,
    memberFeedbackProvidedBy: String,
    memberFeedbackProvidedAt: Date,
    memberFeedbackRemarks: String,
    reappearanceCount: Number,
    remarks: String,
    description: String,
})

module.exports = mongoose.model('Incident',incidentSchema);